package main

import (
	"log"

	"csv-demo/csv_reder"
)

func main() {
	var jsonData = `{
	  "": "",
	  "": "",
	  "account_name": "ディモフ　リエコ",
	  "account_number": "6674317",
	  "account_type": "1",
	  "acquisition_category": "1",
	  "avatar_url": "https://storage.googleapis.com/whr/file/1408059e-8466-217e-d45a-265a64a5e4d3.png",
	  "bank_name": "三井住友銀行",
	  "birthday": "2019-10-15",
	  "branch_name": "Hhhh",
	  "building_kana": "トウキョウトムサシノシキョウナンチョウ５－４－１２",
	  "business_owner_first_name": "グスタボ",
	  "business_owner_last_name": "ドレ　ロドリゲス",
	  "business_owner_phone": "012-2222-3333",
	  "business_owner_residence_city": "千代田区",
	  "business_owner_residence_postal_code": "100-0002",
	  "business_owner_residence_prefecture": "東京都",
	  "business_owner_residence_street": "皇居外苑",
	  "cell_phone": "0301429102",
	  "child_name": "[]",
	  "children": "1",
	  "city": "武蔵野市",
	  "commuter_pass": "123,456",
	  "commuter_period": "1",
	  "commuting_route": "JR中央線（中央総武線）およびJR山手線（埼京線他）　武蔵境駅〜大崎駅",
	  "company__address": "Fabbit 3F",
	  "company__address_kana": "",
	  "company__building": "建物名・部屋番",
	  "company__building_kana": "ファビット 3F 内",
	  "company__city": "千代田区",
	  "company__company_code": "",
	  "company__corporateNumber": "asd",
	  "company__corporate_address": "XXXX",
	  "company__corporate_name": "TETETE",
	  "company__corporate_number": "７００１１０００５９０１0",
	  "company__description": "",
	  "company__employment_insurance_company_number": "",
	  "company__health_insurance_code": "123456",
	  "company__labor_insurance_number": "12-2-22-222222-222",
	  "company__logo_url": "https://storage.googleapis.com/whr/DEV/file/350200db-c7a5-d3c8-2620-63f5d7def1b9.png",
	  "company__name": "HBACT4567",
	  "company__nameKana": "Lam",
	  "company__name_kana": "",
	  "company__office_number": "324",
	  "company__office_reference_number": "efew",
	  "company__phone": "012-122-3333",
	  "company__postal_code": "100-0012",
	  "company__prefecture": "東京都",
	  "company__representative": "Guilherme Costa",
	  "company__representative_first_name": "",
	  "company__representative_last_name": "res11",
	  "company__seal_url": "https://storage.googleapis.com/whr/DEV/file/0c2693f9-b710-fae0-88fe-1852ce63ab14.png",
	  "company__send_address": "池袋",
	  "company__shop_code": "7FD9E69E",
	  "company__street": "日比谷公園",
	  "company__support_email": "https://forms.office.com/r/reYHX0PXw0",
	  "company__welfare_insurance_company_number": "67890",
	  "company_name": "ワークスタイルテック株式会社",
	  "contract_date": "2022-04-20",
	  "contract_period": "無",
	  "copy_of_foreigner_registration_card": "0",
	  "dependent_status": "無",
	  "document_attachment_method": "0",
	  "em_building_kana": "トウキョウトムサシノシキョウナンチョウ５－４－１２",
	  "em_city": "武蔵野市",
	  "em_first_name": "BOYAN VALENTINOV",
	  "em_first_name_kana": "ボヤン　バレンティノフ",
	  "em_last_name": "DIMOV",
	  "em_last_name_kana": "ディモフ",
	  "em_phone": "090-6529-5269",
	  "em_postal_code": "180-0023",
	  "em_prefecture": "東京都",
	  "em_relationship": "夫",
	  "em_street": "境南町５－４－１２",
	  "employee_number": "WHR00063",
	  "employment_status": "2",
	  "first_name": "Min",
	  "first_name_kana": "よし",
	  "gender": "2",
	  "get_qualification_date": "2022-05-24",
	  "home_phone": "080-1274-3646",
	  "hospitalization_certificate": "0",
	  "household": "DIMOV, BOYAN VALENTINOV",
	  "insurance_number": "5057-264225-0",
	  "last_name": "ディモフ",
	  "last_name_kana": "ハロー",
	  "marital_status": "2",
	  "monthly_wage": "44",
	  "my_number": "703717399499",
	  "my_number_select": "1",
	  "nda": "https://storage.googleapis.com/whr/file/0e085190-dc63-28fa-5a7f-f8cae0884c5d.jpg",
	  "occupation": "05",
	  "other_document": "0",
	  "partner_name": "DIMOV, BOYAN VALENTINOV",
	  "payment_mode": "1",
	  "payroll_schedule": "2",
	  "payslip_member_type": "2",
	  "pension_number": "7451-027620",
	  "personal_email": "simin+1015@motify.work",
	  "postal_code": "180-0023",
	  "prefecture": "東京都",
	  "prefecture_code": "21",
	  "reasons_register": "1",
	  "recruitment_channel": "1",
	  "relationship": "3",
	  "residence_certificate": "0",
	  "salary_amount": "500万",
	  "salary_month": "416667",
	  "salary_of_cash": "416667",
	  "start_date": "2022-06-01",
	  "street": "境南町５－４－１２",
	  "type_of_insurance": "1",
	  "type_of_insured_person": "2",
	  "work_week_hours": "33",
	  "work_week_minutes": "4"
	}`
	err := csv_reder.ParserData("template.csv", "records.csv", jsonData)
	if err != nil {
		log.Fatal(err)
	}
}
